### ISSUE TITLE
Project still active

### ISSUE THREAD

**Issue by Portur** [stadt-bielefeld/wms-downloader#6]
Hi,
Last push was 2 years ago. 

@stadt-bielefeld
Is this project still actively maintained?

Would be great if it could be revived.

**Comment by geofreak** [comment]
Thats true, the last push was 2 years ago.

We use that tool every day and it works great.

I am planning a rewrite, with 
* modern JavaScript 
* better code pattern
* better documentation
* and some new features

This project is not dead, but it sleeps until I find time.

If you find mistakes or want new features, write an issue.

**Comment by Portur** [comment]
Great to hear!

I'd love to have support for `xml+svg`.
We tried writing our own but trying to combine svg paths' did not work out the way we expected to.

PS. Is this used in [WMS Downloader](http://geotrix.eu/) maybe?

**Comment by Portur** [comment]
Just to add our goal was to add all svg's to a single object with which we could convert to geojson, seeing as we already had the bounds of all tiles used in the merge.

I think our lack of time was the largest problem but got me to appreciate tools like these.

**Comment by geofreak** [comment]
A good svg support is not easy.

Here my thoughts:
1. The WMS have to support xml+svg
2. Do you know any GIS with support of svg tiles?
3. For support in any GIS a svg tile needs a world file. I don't know an agreement for svg tiles (see []( https://en.wikipedia.org/wiki/World_file))
4. For digital imaging the `wms-downloader` uses GraphicsMagick. I dont't know if GraphicsMagick have a full svg support. I don't think so.

If GraphicsMagick supports the functions `crop` for svg files, it's easy to support svg.
And for the world file I can conceive a file extension for svg files.

Feel you free to check this.

**Comment by geofreak** [comment]
I don't know anything about http://geotrix.eu/.

**Comment by geofreak** [comment]
To merge all tiles I'm using [merge-tiles](https://github.com/stadt-bielefeld/merge-tiles/).

It uses the function `append` of GraphicsMagick. If GraphicsMagick supports the functions `append` for svg files, it's easy to support svg.

Feel you free to check this.

**Comment by geofreak** [comment]
Alternatively, I could use another node module with svg support for digital imaging.

Do you know a good svg node module?

**Comment by Portur** [comment]
No SVG modules per se, but what we tried,

simply parsing the svg using `xml2js`, get the path, use `geoFromSVGXML` by adding the bounds to the svg/xml object, and parse to geojson.

A lot of issues ame after that when some polys in the svg would translate to linestrings, so we had to use `turf.lineToPolygon` to get the actual poly.

**Comment by Portur** [comment]
If you are curious [I dug up the code](https://gist.github.com/Portur/a555f95c03000a1c697977e34306a527). Not very pretty

**Comment by geofreak** [comment]
If the WMS supports svg then it is based on vector data.

Why you don't use the originally vector data? That's very easy to convert the originally data to geojson. 

You make a big detour when you try to convert a WMS tile to geojson. 

Or use a Web Feature Service  (WFS), optionally it supports geojson directly.

**Comment by Portur** [comment]
Our use case unfortunately was no support other than WMS, luckily xml+svg, which brought me here

**Comment by geofreak** [comment]
Sorry, but the job of the wms-downloader is downloading of wms tiles and not to convert svg to geojson.
It's a downloader not a converter.
